{% set name = "prawcore" %}
{% set import = "prawcore" %}
{% set version = "3.0.0" %}
{% set sha256 = "68b7b3fffa8cde623c841e204cb401a5e4cf2c1ef05d63ee7d3c5c37631dbe59" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.4,<4
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.6.0,<3.0

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - {{ import }}

about:
  home: https://github.com/praw-dev/prawcore
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Low-level communication layer for PRAW 4+
  description: Prawcore is a low-level communication layer used by PRAW 4+.
  dev_url: https://github.com/praw-dev/prawcore
  doc_url: https://github.com/praw-dev/prawcore/blob/main/README.rst

extra:
  recipe-maintainers:
    - CAM-Gerlach
    - djsutherland
